### ISSUE TITLE
LICENSE file missing

### ISSUE THREAD

**Issue by crshrprt** [Davit-G/minierosion#1]
Thank you for this interesting plugin.

I can't find if the source is released under a license. Is there a license?

**Comment by Davit-G** [comment]
Thank you for the kind words!

Since this was a small test plugin I forgot to add a license to this repository. License will be bound by my usage of JUCE as the audio framework, which makes this repo licensed under GNU GPL v3 if I'm not wrong

**Comment by Davit-G** [comment]
Added license https://github.com/Davit-G/minierosion/commit/5833e183f3ea204bba77bcc64d218a46b1769d57 for the time being

Thanks for the reminder!

**Comment by Davit-G** [comment]
While you're here if you don't mind me asking, I notice the nature of your Github profile is a little strange considering the number of repositories you have and the number of issues you're raising asking for licenses from developers. Others have raised this concern as well, and I can understand the concerns from the developer's perspective, but seeing your response here https://github.com/lachesis17/Delay-ja-vu/issues/1 definitely puts me at ease.

I'd love to find out where you share your knowledge on the FOSS / linux plugins you've collected over the years, and I'm also wondering how you found this repo specifically since I haven't made a big deal to share it with many people yet. I'd love to contribute in the best way possible and if I know my work is being shared this way I can take steps to make my work more accessible for everybody to use

**Comment by crshrprt** [comment]
Mainly in the unfa's discord/Rocketchat community (probably the largest on the net focusing on music production with FLOSS) and linuxmusicians.com.

I found your repo, and many others, using the GitHub search bar, typing some simple keywords like vst3 or juce and having the dedication to scroll among the results.

**Comment by crshrprt** [comment]
Since you are interested in places where people share FOSS/Linux plugins you could also have a look at:

- http://linuxmusic.rocks/ (I contributed to it by submitting some plugins in the past, no distinction between freeware and FOSS yet)
- https://linuxdaw.org/ (focus on plugins with "nice" GUIs, a lot of proprietary plugins, has distinction between freeware and FOSS, license info not always accurate)
- https://libreav.org/ (only FOSS, not currently working)
- My Github's [starred repositories](https://github.com/crshrprt?tab=stars), I collected quite a "few" interesting projects there. :)

**Comment by Davit-G** [comment]
Thanks for sending those links over ❤️ very much appreciated
